version: '3'

services:
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    ports:
      - 84:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=europe/athens
    volumes:
      - ./heimdall:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - com.centurylinklabs.watchtower.enable=true
    