version: '3'

services:
  db:
    image: mariadb
    container_name: sample-database
    restart: unless-stopped
    logging:
      options:
        max-size: 0.5g
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 3306:3306
    volumes:
      - sample-database-vol:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: secret_password
      MARIADB_AUTO_UPGRADE: true

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-smaple-database
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: "root"
      PMA_PASSWORD: "secret_password"
    logging:
      options:
        max-size: 0.5g

volumes:
  sample-database-vol: {}
