# image,docs: https://hub.docker.com/_/wordpress/

version: '3.8'

services:

  wordpress:
    image: $REPO:$VERSION
    container_name: $ID
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    ports:
      - $HTTP_PORT_SET:$HTTP_PORT
    env_file: .env
    volumes:
      - wordpress:/var/www/html
      - ./src/php_exra.ini:/usr/local/etc/php/conf.d/php_exra.ini

  wordpress-cli:
    image: $REPO:cli
    container_name: $ID-cli
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    command: |
      /bin/bash -c "
      if [ -z \"$URL\" ]; then
        echo 'URL is empty, no need to change, exiting...'
        sleep 3
        exit 0
      fi
      if [[ $URL =~ ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$ ]]; then
        wp_url=$URL:$HTTP_PORT_SET
        echo 'URL is IP'
        sleep 3
      else
        wp_url=$URL
        echo 'URL is not IP'
      fi
      sleep 3
      wp option update home \"http://$$wp_url\"
      wp option update siteurl \"http://$$wp_url\"
      "

  mariadb:
    image: mariadb:$DB_VERSION
    container_name: $ID-mariadb
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_log_buffer_size=30M
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $ID
      MYSQL_USER: $ID
      MYSQL_PASSWORD: $POWER_PASSWORD
      MYSQL_ROOT_PASSWORD: $POWER_PASSWORD

volumes:
  wordpress:
  mysql_data:


networks:
  default:
    name: $NETWORK
    external: true
